### ISSUE TITLE
Example #3 (Color Picker) not functional on Bip 5 device emulator

### ISSUE THREAD

**Issue by tozachroberts** [silver-zepp/zeppos-autogui#4]
I've been exploring autogui with my older generation device (Amazfit Bip S), which I am using the emulator Bip 5 to simulate. I believe these devices are OS version 2.0 compatible, so I've been trying to load up a mini-app with some of the examples. While the Example #1 (Hello World) works exactly as documented with no changes after embedding it in a mini-app Page, the Example #3 (Color Picker) only partially functions. It does draw the rectangles, and the onRelease event is firing and updating the text box, but the color application in the fillRect call and the color adjustments in the onRelease and onPress events don't work as documented. The rectangles are rendered black and never change color. Any ideas on if this should work and how I might go about debugging it?

```javascript
import AutoGUI, {multiplyHexColor} from "@silver-zepp/autogui"
const gui = new AutoGUI();

Page({
  state: {},
  build() {
    const colors_arr = ['#f2559d','#7b29cc','#984ce5'];
    // create a modifiable text field
    this.txt_selected_color = gui.text("Selected color: #000000");
    gui.newRow();
    for (const color of colors_arr) {
      // create a fill rect object
      const rect = gui.fillRect(color);

      // assign "on release" actions
      rect.onRelease(() => {
        //sound.play();
        this.txt_selected_color.update({ text: "Selected color: " + color.toString(16) });
        rect.update({ color: color }); // reset the rect color
      });

      // assign "on press" action: dim the rect color by 30%
      rect.onPress(() => { rect.update({ color: multiplyHexColor(color, 0.7) }) });
    }
    gui.render();
  }
})
``` 
![Screenshot_20240429_222847](https://github.com/silver-zepp/zeppos-autogui/assets/18409369/3f426b47-bf90-476d-867f-b1c3cd9f4825)
![Screenshot_20240429_223119](https://github.com/silver-zepp/zeppos-autogui/assets/18409369/759569e9-c78b-4759-8fe4-9454a5f10106)

**Comment by tozachroberts** [comment]
Similarly, if I convert away from fillRect to button instances, the rendering of color doesn't behave as documented (but does render with a default red button color):

```javascript
Page({
  state: {},
  build() {
    //const colors_arr = [COLOR_RED, COLOR_ORANGE, COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE, COLOR_INDIGO, COLOR_VIOLET];
    const colors_arr = ['#f2559d','#7b29cc','#984ce5'];
    // create a modifiable text field
    this.txt_selected_color = gui.text("Selected color: #000000");
    gui.newRow();
    for (const color of colors_arr) {
      var b = gui.button(color, () => {
        this.txt_selected_color.update({ text: "Selected color: " + color.toString(16) });
      });
    }
    gui.render();
  }
})
```
![Screenshot_20240429_223711](https://github.com/silver-zepp/zeppos-autogui/assets/18409369/a6f5dadb-fe40-4855-b4e3-93d376d742e2)

**Comment by silver-zepp** [comment]
ZeppOS doesn't use hex colors, instead, you have to provide a numeric value just like it's done [here](https://github.com/silver-zepp/zeppos-autogui/blob/master/autogui-example/include/constants.js). Or write a converter. The "selected color" field just uses it for a visual part.

**Comment by tozachroberts** [comment]
Genius. I was wondering where those COLOR_ constants were defined and had thus far failed to find them. After converting to hex definitions for colors, all is right with the example. Thanks for the amazing turnaround time.

![Screenshot_20240429_230049](https://github.com/silver-zepp/zeppos-autogui/assets/18409369/afb0829e-cd82-4c55-8594-40bdff3450ec)
